# SITE CONFIGURATION
title: '绍兴店口' # 主题
author: wes # 作者信息
description: > # Meta description of Homepage
  详细描述内容.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://baidu.com" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Wes
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: '首页', link: '/'}
  - {name: '新闻动态', link: '/news'}
  - {name: '走进店口', link: '/about'}
  - {name: '互动交流', link: '/contact'}

tagline: >
  白塔湖是诸暨市境内最大的湖畈，面积为38平方千米。湖内河道交叉，水网密布，晴好天气漾舟湖上，只见两岸碧野无际，风吹浪起，湖面烟波浩渺，舟楫点点。

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: 836790625@qq.com # email for form submission

github_username:  weswu # replace with your_github_username or comment to remove link from footer
instagram_username: weswu # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: wes # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
# exclude: ['README.md', 'node_modules', 'script', 'package.json', 'package-lock.json', 'Gemfile', 'Gemfile.lock', 'vendor', 'npm-debug.log', 'gulpfile.js', 'sleek.jpg']
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude_from_watch:
- css
